# Generated by Django 5.0 on 2023-12-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_mymodel_boolean_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='char_field',
            field=models.CharField(default='DragonFly', max_length=255),
        ),
    ]
