# Generated by Django 5.0 on 2023-12-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_mymodel_char_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='id',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='auto_field',
            field=models.AutoField(default=True, primary_key=True, serialize=False),
        ),
    ]
