# Generated by Django 5.0 on 2023-12-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_remove_mymodel_id_mymodel_auto_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='date_time_field',
            field=models.DateTimeField(default=12.23),
        ),
    ]
