# Generated by Django 5.0 on 2023-12-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_mymodel_date_time_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='email_field',
            field=models.EmailField(blank=True, default=None, max_length=254),
        ),
    ]
