# Generated by Django 5.0 on 2023-12-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_mymodel_email_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='text_field',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='time_field',
            field=models.TimeField(default='12:00'),
        ),
    ]
