# Generated by Django 5.0 on 2023-12-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_mymodel_text_field_mymodel_time_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='big_integer_field',
            field=models.BigIntegerField(default=100000),
        ),
    ]
