# Generated by Django 5.0 on 2023-12-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_mymodel_binary_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='duration_field',
            field=models.DurationField(default=10),
        ),
    ]
