# Generated by Django 5.0 on 2023-12-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0012_mymodel_float_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='slug_field',
            field=models.SlugField(default=200),
        ),
    ]
