# Generated by Django 5.0 on 2023-12-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0013_mymodel_slug_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='small_integer_field',
            field=models.SmallIntegerField(default=0),
        ),
    ]
