# Generated by Django 5.0 on 2023-12-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0014_mymodel_small_integer_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='positive_big_integer_field',
            field=models.PositiveBigIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='positive_integer_field',
            field=models.PositiveIntegerField(default=1111),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='positive_small_integer_field',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
