# Generated by Django 5.0 on 2023-12-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0016_mymodel_decimal_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='generic_ip_address_field',
            field=models.GenericIPAddressField(default=8.8),
        ),
    ]
