# Generated by Django 5.0 on 2023-12-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0018_mymodel_file_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='file_path_field',
            field=models.FilePathField(default=None, path='/path/to/files/'),
        ),
    ]
