# Generated by Django 5.0 on 2023-12-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0019_mymodel_file_path_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='image_field',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
