# Generated by Django 5.0 on 2023-12-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0020_mymodel_image_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='integer_field',
            field=models.IntegerField(default=2),
        ),
    ]
