# Generated by Django 5.0 on 2023-12-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0021_mymodel_integer_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='json_field',
            field=models.JSONField(default=None),
        ),
    ]
