# Generated by Django 5.0 on 2023-12-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0022_mymodel_json_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='url_field',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='uuid_field',
            field=models.UUIDField(default=None),
        ),
    ]
