# Generated by Django 5.0 on 2023-12-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0023_mymodel_url_field_mymodel_uuid_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='comma_separated_field',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
